version: '3.8'

services:
  gokboru_core:
    build: .
    image: gokboru-sotm:latest
    container_name: gokboru_container
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/home/gokboru_ws/src/teknofest_insansiz_kara_araci
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    restart: unless-stopped

  simulation:
    image: gokboru-sotm:latest
    container_name: gokboru_sim
    network_mode: host
    command: /bin/bash -c "source /opt/ros/humble/setup.bash && make simulate"
    depends_on:
      - gokboru_core
